//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INTECEntities : DbContext
    {
        public INTECEntities()
            : base("name=INTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientTypes> ClientTypes { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<ContactTypes> ContactTypes { get; set; }
        public virtual DbSet<Deparments> Deparments { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Restrictions> Restrictions { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserRestrictions> UserRestrictions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
